# Generated by Django 5.0.6 on 2024-06-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0002_leadnews_news_parents_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeadNews',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Parents',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
