# Generated by Django 5.0.7 on 2024-08-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('css_path', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
