# Generated by Django 5.0.6 on 2024-06-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0003_withoutborders_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withoutborders',
            name='image',
        ),
        migrations.AlterField(
            model_name='withoutborders',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
